#!/bin/bash
trap 'echo `date`;exit' 2
L=`who | cut -d' ' -f1 | sort | uniq`
P=`ps aux | tail -n+2 | awk '{print $1}'`

while [ 0 ]; do
	for j in $L; do
		echo "User: "$j
		echo $P | grep -o $j | wc -l
	done
	sleep 2
done