#!/bin/bash

trap 'echo `date`;exit' 2
if [ $# -eq 0 ]; then
	t=10
else
	t=$1
fi

while [ true ]; do
	D=`ps aux | awk '{print $10}' | awk -F: '{print $1*60+$2}'`
	N=0
	for j in $D; do
		if [ $j -gt $t ]; then
			((N++))
		fi
	done
	echo $N
	sleep 5
done